
import React from 'react';

const ArchitectureDiagram: React.FC = () => {
  // Mermaid definition representing the RAIN System Architecture
  const mermaidCode = `
graph TD
  %% Styles
  classDef client fill:#e0f2fe,stroke:#0284c7,stroke-width:2px,color:#0f172a,rx:10,ry:10;
  classDef server fill:#f0fdf4,stroke:#16a34a,stroke-width:2px,color:#0f172a,rx:10,ry:10;
  classDef db fill:#fefce8,stroke:#ca8a04,stroke-width:2px,color:#0f172a,rx:5,ry:5;
  classDef ai fill:#faf5ff,stroke:#9333ea,stroke-width:2px,color:#0f172a,rx:10,ry:10;
  classDef user fill:#f1f5f9,stroke:#475569,stroke-width:2px,color:#0f172a,circle;

  user((User Access)):::user
  
  subgraph Client ["Client Layer (Frontend)"]
    direction TB
    react[React 19 SPA / Vite]:::client
    subgraph Portals
        hr[HR Portal]:::client
        it[IT Fleet Control]:::client
        emp[Employee UAT]:::client
    end
  end

  subgraph Cloud ["Azure Cloud Infrastructure"]
    direction TB
    lb[Load Balancer / Ingress]:::server
    
    subgraph Compute ["Compute Service"]
        node[Node.js Express Server]:::server
        static[Static Assets]:::server
    end
    
    subgraph Persistence ["Data Layer"]
        sql[(Azure SQL Database)]:::db
    end
  end

  subgraph External ["External Services"]
    gemini[Google Gemini API]:::ai
  end

  user -->|HTTPS / SSL| lb
  lb -->|Serve| react
  react --> hr & it & emp
  
  hr & it & emp -->|REST API| node
  
  node <-->|TDS Protocol| sql
  node <-->|GenAI SDK| gemini
  
  sql -.->|Sync Ledger| it
  gemini -.->|Insights| it
  `;

  // Encode for mermaid.ink service
  const jsonState = JSON.stringify({
    code: mermaidCode,
    mermaid: { 
      theme: 'default',
      themeVariables: {
        fontFamily: 'Inter',
        fontSize: '16px'
      }
    },
  });
  const base64State = btoa(jsonState);
  const imageUrl = `https://mermaid.ink/img/${base64State}`;

  const handleDownload = async () => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'rain-architecture-diagram.jpg';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (e) {
      alert("Automatic download failed. You can right-click the image and select 'Save Image As'.");
    }
  };

  return (
    <div className="space-y-8 animate-[fadeIn_0.3s]">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tighter uppercase italic">System Architecture</h1>
          <p className="text-slate-500 font-medium mt-1">Technical Topology & Data Flow Diagram</p>
        </div>
        <button onClick={handleDownload} className="bg-slate-900 text-white px-8 py-4 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-slate-800 transition-all shadow-xl shadow-slate-900/20 active:scale-95 flex items-center gap-3">
          <i className="fa-solid fa-file-export"></i> Export as Picture
        </button>
      </div>

      <div className="bg-white rounded-[3rem] p-12 border border-slate-200 shadow-sm flex flex-col items-center justify-center min-h-[600px] relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-teal-400 via-emerald-400 to-cyan-400"></div>
        
        <img src={imageUrl} alt="RAIN Architecture" className="max-w-full h-auto drop-shadow-2xl rounded-xl" />
        
        <div className="mt-12 flex items-center gap-6 text-slate-300">
            <div className="h-px bg-slate-100 flex-1 w-32"></div>
            <p className="text-[10px] font-mono font-black uppercase tracking-[0.3em]">Generated by RAIN Systems</p>
            <div className="h-px bg-slate-100 flex-1 w-32"></div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-6">
          <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100">
              <h3 className="font-black text-slate-900 text-xs uppercase tracking-widest mb-2">Frontend</h3>
              <p className="text-xs text-slate-500">React 19, Vite, Tailwind CSS. Deployed as static assets served via Node/Express.</p>
          </div>
          <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100">
              <h3 className="font-black text-slate-900 text-xs uppercase tracking-widest mb-2">Backend</h3>
              <p className="text-xs text-slate-500">Node.js Express API. Handling business logic, UAF generation, and Azure SQL transactions.</p>
          </div>
          <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100">
              <h3 className="font-black text-slate-900 text-xs uppercase tracking-widest mb-2">Integrations</h3>
              <p className="text-xs text-slate-500">Google Gemini for AI insights. Azure SQL for persistent relational ledger.</p>
          </div>
      </div>
    </div>
  );
};

export default ArchitectureDiagram;
